### ISSUE TITLE
Open ID 2 obsolete?

### ISSUE THREAD

**Issue by tkdrob** [TeddiO/pySteamSignIn#8]
It looks like Open ID 2 is obsolete. I get nxdomain with generated url. Is it possible this library can be updated to support Open ID Connect?

**Comment by TeddiO** [comment]
Do you have an example of what you're trying to do? The examples provided are still functioning for me as are my own projects. 

OpenID Connect won't work unless Valve have moved to OAuth2 standards.

**Comment by TeddiO** [comment]
(Additionally, Steamworks makes no suggestion OpenID 2 has gone: https://partner.steamgames.com/doc/features/auth#website)

**Comment by tkdrob** [comment]
Thanks for the swift response. I must be doing it wrong and it is just not clear enough for me from the example on how to use it. The below usage is obviously wrong. Invalid url for both encoded and unquoted. Browsing myself to the url part yields nxdomain.

Thanks for the help in advance.

```
login = SteamSignIn()
url = login.ConstructURL("https://my.home-assistant.io/")
session = async_get_clientsession(self.hass) #get aiohttp session
await session.get(url)
```

```
2023-01-06 15:34:18.136 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/Users/tkdrob/core/venv/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/Users/tkdrob/core/venv/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/Users/tkdrob/core/venv/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/Users/tkdrob/core/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/Users/tkdrob/core/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/Users/tkdrob/core/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/Users/tkdrob/core/homeassistant/components/http/ban.py", line 81, in ban_middleware
    return await handler(request)
  File "/Users/tkdrob/core/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/Users/tkdrob/core/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/Users/tkdrob/core/homeassistant/components/config/config_entries.py", line 148, in post
    return await super().post(request)
  File "/Users/tkdrob/core/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/Users/tkdrob/core/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/Users/tkdrob/core/homeassistant/data_entry_flow.py", line 230, in async_init
    flow, result = await task
  File "/Users/tkdrob/core/homeassistant/data_entry_flow.py", line 257, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/Users/tkdrob/core/homeassistant/data_entry_flow.py", line 375, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/Users/tkdrob/core/homeassistant/components/steam_online/config_flow.py", line 86, in async_step_user
    await session.get(url)
  File "/Users/tkdrob/core/venv/lib/python3.10/site-packages/aiohttp/client.py", line 507, in _request
    req = self._request_class(
  File "/Users/tkdrob/core/venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 305, in __init__
    self.update_host(url)
  File "/Users/tkdrob/core/venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 366, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL: openid.ns=http:%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=checkid_setup&openid.return_to=https:%2F%2Fmy.home-assistant.io%2F&openid.realm=https:%2F%2Fmy.home-assistant.io%2F&openid.identity=http:%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.claimed_id=http:%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select
```

**Comment by tkdrob** [comment]
While waiting, I noticed that this must just be the parameters for the url. smh

**Comment by tkdrob** [comment]
So right now this seems to be working but I may have to use `session.get` instead? I would be directing the user to the steam page at this point.

```
login = SteamSignIn()
url = login.ConstructURL("https://my.home-assistant.io/")
url = f"https://steamcommunity.com/openid/login?{url}"
session = async_get_clientsession(self.hass)
await session.post(url)
```

**Comment by TeddiO** [comment]
I'm not that familiar with aiohttp unfortunately (I've used it briefly here and there but never for websites), however https://docs.aiohttp.org/en/stable/web_quickstart.html#redirects might be what you're looking for to redirect users.

**Comment by tkdrob** [comment]
Not to worries, I am familiar with it. Turns out the project I'm working with does not support OIDC rn. Taking it up with the founder. Thanks
